### ISSUE TITLE
1.4.0-1 no longer buildable

### ISSUE THREAD

**Issue by julie-is-late** [kiendang/aur-nvidia-container-runtime-hook#1]
It seems that the `v1.4.0-1` tar release was pulled from the github releases, meaning that this package can no longer build. 

Seeing as it is being replaced fully by the toolkit package, fixing this will basically only help people who need it for `nvidia-docker`, which is going to be going away at some point as well.

**Comment by kiendang** [comment]
Can just orphan/delete this and the bin package. `nvidia-docker` should only depend on `nvidia-container-runtime` anyway. And `nvidia-container-toolkit` provides `nvidia-container-runtime-hook` so it should be fine.

**Comment by julie-is-late** [comment]
sounds good. the provides statement was gathered from the CentOS rpm package definition so it should be genuine. I'll close this then.
