### ISSUE TITLE
Delete nvidia-container-runtime-hook aur package

### ISSUE THREAD

**Issue by kiendang** [kiendang/aur-nvidia-container-runtime-hook#2]
@jshap70 I think deleting this package is the most appropriate thing to do. `nvidia-container-runtime-hook` doesn't exist anymore. The link doesn't work. And with `nvidia-container-toolkit` replacing it packages that depend on it (though they shouldn't at this point) would be fine. Thoughts?

**Comment by julie-is-late** [comment]
we get killed on time change, so hard to coordinate haha. 

I am ok with this, although it seems a little weird. I've seen cases where people have deleted a package for similar reasons only to have someone else reupload the pkgbuild again and go "idk why they deleted it here it is again". Basically I think it's a good way to make every `nvidia-docker` user unhappy, but really `nvidia-docker` is the one who needs to update their dependency. 

Maybe I'll leave a comment on `nvidia-docker` telling them to change their dependency, and if they don't reply I'll just make a request to become a maintainer on it lol. Once that package is changed I'm happy deleting this entirely.

**Comment by kiendang** [comment]
> I've seen cases where people have deleted a package for similar reasons only to have someone else reupload the pkgbuild again and go "idk why they deleted it here it is again"

In this case the pkgbuild doesn't even work tho coz the link is dead lol

> Maybe I'll leave a comment on nvidia-docker telling them to change their dependency, and if they don't reply I'll just make a request to become a maintainer on it lol. Once that package is changed I'm happy deleting this entirely.

Sounds good to me. Thanks!

**Comment by kiendang** [comment]
Saw this in [nvidia-docker aur](https://aur.archlinux.org/packages/nvidia-docker/) was that you?
<img width="87" alt="Screen Shot 2019-08-03 at 11 49 29 PM" src="https://user-images.githubusercontent.com/6521018/62414064-739c4600-b649-11e9-8061-dca3396e179f.png">

**Comment by julie-is-late** [comment]
haha yeah... 
requests take on the order of 2 weeks so I just went ahead and filed it.

**Comment by julie-is-late** [comment]
can you take a once over on this patch? https://github.com/jshap70/aur-nvidia-docker/commit/9fab518213bba83d3f736be0a0011042f99b4368

if all looks good I'll push it and then we can delete `-hook` :)

**Comment by kiendang** [comment]
Why use `_actual_version` instead of changing `pkgver` to 2.1.1? Other than that looks good to me.

**Comment by julie-is-late** [comment]
the took itself dumps a version string equaling the old one and not 2.1.1, so I left it. I can ask if they meant to bump it though.

**Comment by kiendang** [comment]
Looks like it's a bug that they just fixed in NVIDIA/nvidia-docker@315b92b0b7121616c920336bff2719aa0c3b99b4 in master and will be included in 2.2.0. They did intend to bump the version internally.

https://github.com/NVIDIA/nvidia-docker/blob/v2.1.1/Makefile#L6

I prefer still bumping `pkgver` to 2.1.1 following the official Ubuntu, CentOS package. The internal version would just be a bug.

**Comment by julie-is-late** [comment]
good catch, I'll update it then and push it out. thanks.

**Comment by julie-is-late** [comment]
pushed, and submitted a deletion request to [nvidia-container-runtime-hook](https://aur.archlinux.org/packages/nvidia-container-runtime-hook/)

**Comment by kiendang** [comment]
Thank you!
